### ISSUE TITLE
Add new CA certs for HTTPS downloads

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/special-resource-operator#2]
SRO currently uses the system's CA certificate store (Debian's `ca-certificates`, which relies on the Mozilla CA list) to trust the servers from which it is downloading Helm charts.
It is desirable to add a mechanism that dynamically loads additional CA certificates (e.g. through a ConfigMap) into SRO, to cover cases where the server offers a certificate signed by an untrusted CA.

**Comment by zvonkok** [comment]
If recipes need self-signed certificates than they should rely on cert-manager, either install it as a dependency or rely on the relates kube distributions mechanism to provide it. Then just use the annotation to inject the certificates into your resources.

**Comment by qbarrand** [comment]
This issue is rather about allowing SRO to download recipes from an HTTPS source that offers a self-signed certificate. In that situation, SRO would not be able to establish the TLS connection.

**Comment by zvonkok** [comment]
Sure but this applies to SRO as well, rely on cert-manager, create a Secret with the inject annotation during SRO deployment. 
If empty do not care, if populated, because it is needed then use it and add it to the key chain.

**Comment by zvonkok** [comment]
Of if someone does not want to rely on cert-manager provide the certs like the Proxy configuration object is doing that for self-signed https connections in the cluster.

**Comment by zvonkok** [comment]
Some proxies are configured as man-in-the-middle proxies where even with your self signed cert one can fail. Those proxies would need to whitelist the source from where it is coming. no way around.
